### ISSUE TITLE
Update to latest sharp

### ISSUE THREAD

**Issue by blowsie** [unindented/grunt-sharp#4]
Sharp version `0.10.0` now supports windows, could you please update grunt-sharp to use this version?

**Comment by blowsie** [comment]
FYI, I manually downloaded this repo, updated sharp manually, ran `npm install` and `grunt sharp`, and the test images were produced as expected.

**Comment by unindented** [comment]
@blowsie Thanks for letting me know. I've pushed a new version of `grunt-sharp` that uses `0.10.0`. I've made it also `0.10.0`, so that both are in sync and it's more predictable what `grunt-sharp` is using behind the curtains.
